### ISSUE TITLE
Include seasonality

### ISSUE THREAD

**Issue by alsnhll** [alsnhll/SEIR_COVID19_Dev#5]

**Comment by mzlevy** [comment]
We don't have great reason to hope for seasonality (in year 1--i think maybe we do expect it in subsequent years) but want to include sliders so we can play out scenarios. To set defaults could use:
For northern temperate regions:
ε seasonal forcing: uniform .25-.75 
θ peak transmissibility: normal peak at 0; sd .1 
taken from the bullet points on page five of neher et al. 
Mike
[Neher_seasonality.pdf](https://github.com/alsnhll/SEIR_COVID19_Dev/files/4350105/Neher_seasonality.pdf)

**Comment by mzlevy** [comment]
epsilon<-.5
theta<-.1
in model:
seasonality<- (1 + epsilon * cos(2*pi*(t-theta)))
      b1<-b1*seasonality
      b2<-b2*seasonality
      b3<-b3*seasonality

**Comment by alsnhll** [comment]
There is now a script to runSpreadSeason.R that runs the dynamics with seasonal variation in the Beta values (same for all Betas). Note that time is in days so the correct function is:
(1 + seas.amp*cos(2*pi*(t-seas.phase)/365))
Seasonality affects all Beta values equally right now
